# Generated by Django 3.2 on 2021-04-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210426_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.IntegerField(choices=[(0, 'Pop'), (3, 'Latin Music'), (9, 'Lounge'), (8, 'Elevator Music'), (7, 'Blues'), (5, 'Classic'), (1, 'Rock'), (4, 'Alternative Rock'), (2, 'Dance & Electro'), (10, 'Funky'), (6, 'Nu Metal')], default=0, verbose_name='Genre'),
        ),
    ]
