# Generated by Django 3.2 on 2021-04-26 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_artist_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.IntegerField(choices=[(9, 'Lounge'), (0, 'Pop'), (7, 'Blues'), (10, 'Funky'), (5, 'Classic'), (1, 'Rock'), (4, 'Alternative Rock'), (2, 'Dance & Electro'), (8, 'Elevator Music'), (3, 'Latin Music'), (6, 'Nu Metal')], default=0, verbose_name='Genre')),
                ('rel_artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='data.artist')),
            ],
        ),
    ]
