# Generated by Django 3.2 on 2021-04-26 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210426_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='rel_artists',
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='data.genre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.IntegerField(choices=[(5, 'Classic'), (6, 'Nu Metal'), (8, 'Elevator Music'), (1, 'Rock'), (9, 'Lounge'), (7, 'Blues'), (3, 'Latin Music'), (2, 'Dance & Electro'), (0, 'Pop'), (10, 'Funky'), (4, 'Alternative Rock')], default=0, verbose_name='Genre'),
        ),
    ]
