# Generated by Django 3.2 on 2021-04-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210426_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Rock'), (4, 'Alternative Rock'), (5, 'Classic'), (10, 'Funky'), (0, 'Pop'), (8, 'Elevator Music'), (6, 'Nu Metal'), (3, 'Latin Music'), (7, 'Blues'), (2, 'Dance & Electro'), (9, 'Lounge')], default=0, verbose_name='Genre'),
        ),
    ]
